const actionTypes = {
   STAGE_COMPLETE: "STAGE_COMPLETE",
   STAGE_NEXT: "STAGE_NEXT",
   SELECT: "SELECT",
   SELECT_ANSWER_BIRD: "SELECT_ANSWER_BIRD",
   STAGE_WRONG_ANSWER: "STAGE_WRONG_ANSWER",
   SET_STAGES_COUNT: "SET_STAGES_COUNT",
   GAME_COMPLETED: "GAME_COMPLETED",
   NEW_GAME: "NEW_GAME"
}

export default actionTypes;